Added support for rolling monthly directories past the 'to keep' monthly directories into 'to keep' monthly directores after fixing a typo in the unit test that masking this missing functionality.

diff --git a/43f b/43f
--- a/43f
+++ b/43f
@@ -549,7 +549,7 @@ function roll_repository_daily_to_monthly() {
 		local src
 		local dst
 		local mtime=''
-		printf -v src "%s/%s/d%02d" "$repo" "$year" "$day"
+		printf -v src "%s/%d/d%02d" "$repo" "$year" "$day"
 		printf -v dst "%s/%d/m%02d" "$repo" "$year" "$month"
 		if $verbose; then echo -n $'\n'"    Moving files & directories from '$src' to '$dst' ("; fi
 		if $mtime_today; then
@@ -573,8 +573,47 @@ function roll_repository_daily_to_monthly() {
 				    success=false
 				fi
 			fi
-		done <<< "$(find "$src"  -mindepth 1 -maxdepth 1 $mtime| sort)"
+		done <<< "$(find "$src" -mindepth 1 -maxdepth 1 $mtime| sort)"
 		
+		
+		if $verbose; then echo "Done."; fi
+	else
+		if $verbose; then echo "ERROR! Repository '${repo}' doesn't exist!"; fi
+		notify "$repo" "ERROR" "The '${repo}' repository doesn't exist!"
+		success=false
+	fi
+	
+	$success
+}
+
+function roll_repository_monthly_to_monthly() {
+	local success=true
+	local repo="$1"
+	local year="$2"
+	local src_month="$3"
+	local dst_month="$4"
+	
+	if does_repository_exist "$repo"; then
+		local src
+		local dst
+		printf -v src "%s/%d/m%02d" "$repo" "$year" "$src_month"
+		printf -v dst "%s/%d/m%02d" "$repo" "$year" "$dst_month"
+		if $verbose; then echo -n $'\n'"    Moving files & directories from '$src' to '$dst'... "; fi
+		
+		# step through all the files in the src dir and move them to dst
+		while IFS= read -r line; do
+			# don't bother processing an empty line
+			if [ -n "$line" ]; then
+				if $verbose; then echo -n $'\n'"      '$line'... "; fi
+				if $dry_run || mv "$line" "$dst/"; then
+					if $verbose; then echo "Done."; fi
+				else
+					if $verbose; then echo "ERROR!"; fi
+					notify "$repo" "ERROR" "An unknown error occurred while attempting to move the '${line}' file/directory into the '${dst}' directory!"
+					success=false
+				fi
+			fi
+		done <<< "$(find "$src" -mindepth 1 -maxdepth 1 | sort)"
 		
 		if $verbose; then echo "Done."; fi
 	else
@@ -689,10 +728,10 @@ function roll_repository_directories() {
 	if does_repository_exist "$repo"; then
 		# calculate today & keep-through dates
 		local today="$d"
-		local keep_through=$(reldate -$((${config_keep_days} - 1 ))d +%d)
+		local keep_through="$(reldate -$((${config_keep_days} - 1 ))d +%d)"
 		if $verbose; then echo "Keeping files through 'd${keep_through}'."; fi
 		
-		# step through the subdirectories and "process" those that are outside the range to preserve (starting with yesterday)
+		# step through the day subdirectories and "process" those that are outside the range to preserve (starting with yesterday)
 		local year=$(reldate -1d +%Y)
 		local month=$(reldate -1d +%m)
 		local day=$(reldate -1d +%d)
@@ -731,7 +770,7 @@ function roll_repository_directories() {
 			if (( 10#$day < 1 )); then
 				day=31
 				month=$(( 10#$month - 1 ))
-				if (( "$month" < 1 )); then
+				if (( 10#$month < 1 )); then
 					month=12
 					(( year-- ))
 				fi
@@ -760,17 +799,66 @@ function roll_repository_directories() {
 			exit 1
 		fi
 		
+		# calculate month keep-through & year dates
+		local keep_through_year="$(reldate -$((${config_keep_months} - 1))m +%Y)"
+		local keep_through_month="$(reldate -$((${config_keep_months} - 1))m +%m)"
+		
+		# step through the month subdirectories and "process" those that are outside the range to preserve (starting with this month)
+		local year=''
+		local month=''
+		while IFS= read -r year; do
+			year="$(basename "$year")"
+			echo "YEAR: $year"
+			# if we've passed our keep through year, always reset to december of the next earliest year
+			if (( $year < $keep_through_year )); then
+				keep_through_year="$year"
+				keep_through_month=12
+			fi
+			
+			for (( month=12; month > 0; month-- )); do
+				# build the directory paths
+				local month_dir
+				local keep_month_dir
+				printf -v month_dir "%s/%d/m%02d" "$repo" "$year" "$(( 10#$month ))"
+				printf -v keep_month_dir "%s/%d/m%02d" "$repo" "$keep_through_year" "$(( 10#$keep_through_month ))"
+				
+				if $verbose; then echo -n "Processing directory '$month_dir'... "; fi
+				# are we we in a month that should be kept?
+				if (( ( $year > $keep_through_year ) || ( ( $year == $keep_through_year) && (10#$month >= 10#$keep_through_month) ) )); then
+					if $verbose; then echo 'Keeping.'; fi
+				# otherwise, if the month is in the keep through year, we should move it to the keep through month
+				elif (( $year == $keep_through_year )); then
+					if $verbose; then echo -n $'\n''  Processing...'; fi
+					
+					# move the contents of the month's directory to the appropriate keep_through month's directory
+					if roll_repository_monthly_to_monthly "$repo" "$year" "$(( 10#$month ))" "$(( 10#$keep_through_month ))"; then
+						if $verbose; then echo "  Done."; fi
+					else
+						echo 'ERROR!'
+						echo "A fatal error occurred while attempting to move the contents of '$month_dir' to '$keep_month_dir'!"
+						echo 'Exiting.'
+						notify "$repo" "ERROR" "A fatal error occurred while attempting to move the contents of '$month_dir' to '$keep_month_dir'!"
+						exit 1
+					fi
+				# if we've gone path the year to keep, then no need to continue
+				else
+					if $verbose; then echo 'Keeping.'; fi
+					break;
+				fi
+			done
+		done <<< "$(Efind "$repo" -mindepth 1 -maxdepth 1 -regex '.*/[0-9]{4}' | sort -nr)"
+		
 		# consolidate files in the monthly directories
 		if $success; then
-			for (( month=1; month<=12; month++ )); do
+			for (( month=1; month <= 12; month++ )); do
 				printf -v month_dir "%s/%d/m%02d" "$repo" "$year" "$month"
 				if $verbose; then echo -n "Consolidating files & directories in '$month_dir'... "; fi
-					if consolidate_repository_monthly "$repo" "$month"; then
-						if $verbose; then echo "Done."; fi
-					else
-						if $verbose; then echo "ERROR!"; fi
-						notify "$repo" "ERROR" "An error occurred while consolidating files & directories in '${month_dir}'!"
-					fi
+				if consolidate_repository_monthly "$repo" "$month"; then
+				    if $verbose; then echo "Done."; fi
+				else
+				    if $verbose; then echo "ERROR!"; fi
+				    notify "$repo" "ERROR" "An error occurred while consolidating files & directories in '${month_dir}'!"
+				fi
 			done
 		fi
 		
